import Head from 'next/head'
import style_home from './home.module.css'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Acceuil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
            <div id={style_home.blog_home}>
            <div className={style_home.blog_home}>
                <div className={style_home.blog_ellipse}>
                    <div className={style_home.ellipse}>
                        <p className={style_home.ellipse_title}>
                            HITECH-PRESENT
                        </p>
                    </div>
                </div>
                <div className={style_home.blog_description}>
                    <p className={style_home.blog_description_title}>HTP</p>
                    <p className={style_home.blog_description_barre}></p>
                    <p className={style_home.blog_description_text}>
                        Aller plus loin. Nous travaillons en partenariat avec des personnes qui souhaitent concevoir un avenir meilleur
                    </p>
                </div>
            </div>
        </div>
        <div className={style_home.sous_blog_description}>
            <h3>Nous créons des sites Web mémorables qui vendent .</h3>
            <p>
            Nous travaillons en partenariat avec des marques comme la vôtre pour créer des sites Web dont vos clients se souviendront, améliorer considérablement vos indicateurs clés et afficher votre marque avec fierté.
            </p>
        </div>
        <div className={style_home.background_sous_description}>
            <h3 className={style_home.background_sous_description_text}>Qu'est-ce qui nous différencie de toutes les autres agences numériques ?</h3>
        </div>
        <div className={style_home.blog_different}>
            <div className={style_home.blog_different_section}>
                <div className={style_home.blog_different_text1}>
                    <h3>Nous sommes spécialisés .</h3>
                    <p>Nous ne sommes pas des généralistes, nous ne vous proposons que ce que nous faisons le mieux : actifs de marque, conception UI/UX, développement full-stack et optimisation de la conversion.</p>
                </div>
                <img src="./image/p3.jpg" className={style_home.img1} />
            </div>
            <div className={style_home.blog_different_section}>
            <img src="./image/p2.jpg" className={style_home.img2} />
                 <div className={style_home.blog_different_text1}>
                    <h3>Nous nous concentrons sur les résultats.</h3>
                    <p>Nous nous soucions de l'impact de notre travail sur votre entreprise ou votre organisation, pas à quoi il ressemble dans notre portefeuille ou dans une vitrine de récompenses.</p>
                </div>
            </div>
            <div className={style_home.blog_different_section}>
                 <div className={style_home.blog_different_text1}>
                    <h3>Nous sommes réactifs.</h3>
                    <p>Nous limitons le nombre de clients que nous acceptons chaque année pour garantir à chacun une expérience client exceptionnelle. Attendez-vous à des réponses en heures, pas en jours.</p>
                </div>
                <img src="./image/p3.jpg" className={style_home.img3} />
            </div>
            <div className={style_home.blog_different_section}>
                <img src="./image/p1.jpg" className={style_home.img4} />
                 <div className={style_home.blog_different_text1}>
                    <h3>Nous allons plus loin.</h3>
                    <p>Nous considérons nos engagements comme des relations, et non comme des accords avec les fournisseurs. En plus de ce que nous produisons, nous éduquons également nos clients sur les meilleures pratiques numériques en cours de route.</p>
                </div>
            </div>
        </div>
        <div className={style_home.offre_site}>
            <div className={style_home.offre_site_text}>
                <h3>Obtenez le site Web de vos rêves .</h3>
                <p>Nous aidons les marques à créer des sites Web d'entreprise et des magasins de commerce électronique mémorables, axés sur la conversion et pérennes.</p>
            </div>
            <div className={style_home.img_site_blog}>
                <img src="./image/site_offre.jpg" className={style_home.img_site_offre} />
            </div>
        </div>
        </div>
    </div>
  )
}
